package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/TacFlow/tac-language/laya"
	"github.com/TacFlow/tac-language/semantic"
)

func read(t *testing.T, p string) string {
	t.Helper()
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func canon(t *testing.T, b []byte) string {
	t.Helper()
	c, err := laya.Canonical(b)
	if err != nil {
		t.Fatal(err)
	}
	return string(c)
}

// `tac episode examples/laya_episode.tac` ≡ the reference JSON (DESIGN §5.5).
func TestEpisodeCommand_ReferenceGolden(t *testing.T) {
	out, _, err := episodeJSON(read(t, "../../examples/laya_episode.tac"), "")
	if err != nil {
		t.Fatal(err)
	}
	if got, want := canon(t, out), canon(t, []byte(read(t, "../../testdata/laya_episode.reference.json"))); got != want {
		t.Fatalf("tac episode differs from the reference:\n got  %s\n want %s", got, want)
	}
}

func TestEpisodeCommand_SelectionRules(t *testing.T) {
	src := read(t, "../../examples/laya_dataset.tac")
	if _, _, err := episodeJSON(src, ""); err == nil || !strings.Contains(err.Error(), "--id") {
		t.Fatalf("3 episodes without --id: err = %v, want a hint about --id", err)
	}
	out, _, err := episodeJSON(src, "ds-estoque-002")
	if err != nil || !strings.Contains(string(out), `"ds-estoque-002"`) {
		t.Fatalf("--id ds-estoque-002: %v %s", err, out)
	}
	if _, _, err := episodeJSON(src, "nope"); err == nil {
		t.Fatal("unknown --id must fail")
	}
	if _, _, err := episodeJSON(read(t, "../../examples/laya_gate.tac"), ""); err == nil {
		t.Fatal("a file without episodes must fail")
	}
}

// `tac compile --json` has every top-level list, even when empty.
func TestCompileJSON_ProgramShape(t *testing.T) {
	out, _, err := programJSON(read(t, "../../examples/laya_episode.tac"), nil, nil, semantic.ModeDevelopment)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(out, &m); err != nil {
		t.Fatal(err)
	}
	for _, k := range []string{"flows", "tasks", "models", "episodes", "datasets"} {
		if _, ok := m[k]; !ok {
			t.Errorf("missing %q in %s", k, out)
		}
	}
	if string(m["flows"]) != "[]" || string(m["tasks"]) != "[]" {
		t.Errorf("flows/tasks should be empty arrays: %s", out)
	}
}

// --tasks: a registry file makes gate labels checkable (TAC-LAYA-002).
func TestCompileJSON_TasksRegistry(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "tasks.json")
	if err := os.WriteFile(p, []byte(`[{"name":"acao","questions":[{"id":"acao","type":"choice","instructions":"?",
		"options":[{"label":"proceed"},{"label":"reuse"},{"label":"ask"}]}]}]`), 0o644); err != nil {
		t.Fatal(err)
	}
	tasks, err := loadTasks(p)
	if err != nil {
		t.Fatal(err)
	}
	_, diags, err := programJSON(read(t, "../../examples/laya_gate.tac"), nil, tasks, semantic.ModeDevelopment)
	if err == nil {
		t.Fatal("gate[skip] is not a label of the registered task: compile must fail")
	}
	found := false
	for _, d := range diags {
		if d.Code == "TAC-LAYA-002" && strings.Contains(d.Message, `"skip"`) {
			found = true
		}
	}
	if !found {
		t.Fatalf("want TAC-LAYA-002 for [skip], got %v", diags)
	}
	if _, err := loadTasks(filepath.Join(dir, "missing.json")); err == nil {
		t.Fatal("a missing --tasks file must be an error")
	}
}

// Golden IR of the six LAYA examples (DESIGN §10): testdata/<name>.compiled.json,
// generated by the compiler and reviewed, compared structurally (JCS) with
// the "language" block removed — it moves with every release (F) and has its
// own tests.
func TestCompileJSON_Goldens(t *testing.T) {
	paths, err := filepath.Glob("../../examples/laya_*.tac")
	if err != nil || len(paths) != 6 {
		t.Fatalf("want the 6 LAYA examples, got %v (%v)", paths, err)
	}
	for _, p := range paths {
		name := strings.TrimSuffix(filepath.Base(p), ".tac")
		t.Run(name, func(t *testing.T) {
			out, _, err := programJSON(read(t, p), nil, nil, semantic.ModeDevelopment)
			if err != nil {
				t.Fatal(err)
			}
			got := canon(t, dropLanguage(t, out))
			want := canon(t, dropLanguage(t, []byte(read(t, "../../testdata/"+name+".compiled.json"))))
			if got != want {
				t.Fatalf("IR differs from testdata/%s.compiled.json:\n got  %s\n want %s", name, got, want)
			}
		})
	}
}

func dropLanguage(t *testing.T, b []byte) []byte {
	t.Helper()
	var m map[string]interface{}
	if err := json.Unmarshal(b, &m); err != nil {
		t.Fatal(err)
	}
	flows, _ := m["flows"].([]interface{})
	for _, f := range flows {
		delete(f.(map[string]interface{}), "language")
	}
	out, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	return out
}
